# This uses travis-ci.org to automate releasing Snap!
language: generic
# We don't actually have tests to run...
script: exit 0;
# We need sshpass to sync to berkeley. (for now.)
before_install:
  - sudo apt-get update
  - sudo apt-get install sshpass
jobs:
  include:
    - stage: deploy
      script: skip
      deploy:
        # This deploys to cs10.org/snap/
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          repo: cs10/snap
          target-branch: master
          on:
            repo: jmoenig/Snap--Build-Your-Own-Blocks
            condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+
            all_branches: true
        # deploy to the Snap!Cloud repo
        # - provider: script
        #   script: |
        #      git clone --depth=1 --recursive https://github.com/bromagosa/snapCloud
        #      cd snapCloud/snap
        #      git fetch origin --tags
        #      release=$(git describe --tags `git rev-list --tags --max-count=1`)
        #      git checkout $release
        #      cd ..; git commit -m "[ci]: automatically checkout ${release}"
        #      git push origin master
        #   on:
        #     repo: jmoenig/Snap--Build-Your-Own-Blocks
        #     condition: $TRAVIS_TAG =~ ^v[0-9]+
        #     all_branches: true
        # deploy master to snap.berkeley.edu/snapsource/dev
        - provider: script
          script: sshpass -p "${REMOTE_PASSWORD}" rsync -avz cycomachead/snap/ ${ACCOUNT}:~/snapsource/
          on:
            repo: jmoenig/Snap--Build-Your-Own-Blocks
            branch: master
        # deploy a release to main snap URL
        - provider: script
          script: sshpass -p "${REMOTE_PASSWORD}" rsync -avz cycomachead/snap/ ${ACCOUNT}:~/snapsource/
          on:
            repo: jmoenig/Snap--Build-Your-Own-Blocks
          condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+
          all_branches: true
