# This uses travis-ci.org to automate releasing Snap!
language: generic
# We don't actually have tests to run...
script: exit 0;
# Creating a release creates a "branch".
jobs:
  include:
    - stage: deploy
      script: skip
      deploy:
        # This deploys to cs10.org/snap/
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          repo: cs10/snap
          target-branch: master
          on:
            repo: cycomachead/snap
            # repo: jmoenig/Snap--Build-Your-Own-Blocks
            condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+
            all_branches: true
        # deploy to the Snap!Cloud repo
        # - provider: script
        #   script: bash scripts/deploy.sh staging
        #   on:
        #     repo: jmoenig/Snap--Build-Your-Own-Blocks
        #     condition: $TRAVIS_TAG =~ ^v[0-9]+
        # deploy master to snap.berkeley.edu/snapsource/development
        # - provider: script
        #   script: scp -r ./* michael@abbenay.cs.berkeley.edu:~/dev/
        #   on:
        #     branch: master
        # deploy a release to berkeley...
        # - provider: script
        #   script: scp -r ./* michael@abbenay.cs.berkeley.edu:~/dev/
        #   on:
        #     repo: cycomachead/snap
        #     repo: jmoenig/Snap--Build-Your-Own-Blocks
        #   condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+
        #   all_branches: true
