# Deploy Snap! when a release is created.

# Creating a release creates a "branch".
deploy:
  # This deploys to cs10.org/snap/
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: false
    repo: cs10/snap
    target-branch: master
    on:
      repo: jmoenig/Snap--Build-Your-Own-Blocks
      condition: $TRAVIS_BRANCH =~ ^v[0-9]+
  # deploy to the Snap!Cloud repo
  # - provider: script
  #   script: bash scripts/deploy.sh staging
  #   on:
  #     repo: jmoenig/Snap--Build-Your-Own-Blocks
  #     condition: $TRAVIS_BRANCH =~ ^v[0-9]+
  # deploy master to snap.berkeley.edu/snapsource/development
  # - provider: script
  #   script: bash scripts/deploy.sh staging
  #   on:
  #     branch: master